dependencies:

- name: prometheus-operator
  version: 8.15.*
  repository: "https://charts.helm.sh/stable"
  alias: prometheusoperator
  condition: prometheusoperator.enabled

- name: prometheus-pushgateway
  version: 1.4.*
  repository: "https://charts.helm.sh/stable"
  alias: pushgateway
  condition: pushgateway.enabled

- name: loki-stack
  version: 0.37.*
  repository: "https://grafana.github.io/loki/charts"
  condition: loki-stack.enabled
